version: '1.0'

services:

  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ../.env
    restart: always

  backend:
    image: belyanski/personal_website:latest
    restart: always
    volumes:
      - static_value:/app/static_backend/
    depends_on:
      - db
    env_file:
      - ../.env

  nginx:
    image: nginx:1.19.3
    ports:
      - "9000:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - static_value:/var/html/static_backend/
    depends_on:
      - backend
    restart: always

volumes:
  static_value:
  postgres_data: